add nginx

diff --git a/pre-buildspec.yml b/pre-buildspec.yml
--- a/pre-buildspec.yml
+++ b/pre-buildspec.yml
@@ -32,33 +32,33 @@ phases:
   build:
     commands:
       - echo "Applying Kubernetes resources..."
-      - kubectl apply -f aws-logging/cloudwatch-logging.yaml --kubeconfig /root/.kube/config
-      - echo "Applying CRDs for LB Controller..."
-      - kubectl apply -f LB-Controller/crds.yaml --kubeconfig /root/.kube/config
-      - echo "Checking if ServiceAccount aws-load-balancer-controller exists..."
-      - SA_NAME=$(kubectl get serviceaccount aws-load-balancer-controller -n kube-system -o jsonpath='{.metadata.name}' 2>/dev/null || echo "")
-      - if [ -z "$SA_NAME" ]; then
-          echo "ServiceAccount not found, creating...";
-          kubectl create serviceaccount aws-load-balancer-controller -n kube-system;
-        else
-          echo "ServiceAccount already exists, skipping creation.";
-        fi
-      - kubectl annotate serviceaccount aws-load-balancer-controller eks.amazonaws.com/role-arn=$EKS_LB_ROLE_ARN -n kube-system --overwrite
-      - helm repo add eks https://aws.github.io/eks-charts
-      - helm repo update
-      - echo "Checking if Helm release aws-load-balancer-controller exists..."
-      - helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller --namespace kube-system --set clusterName="$EKS_CLUSTER_NAME" --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region="$CLUSTER_REGION" --set vpcId="$VPC_ID";
-      - echo "Waiting for aws-load-balancer-controller pod to be ready..."
-      - kubectl wait --for=condition=Available deployment/aws-load-balancer-controller -n kube-system --timeout=300s
-      - echo "aws-load-balancer-controller is now running. Applying nginx deployment..."
-      - kubectl apply -f nginx/nginx.yaml
+      #- kubectl apply -f aws-logging/cloudwatch-logging.yaml --kubeconfig /root/.kube/config
+      #- echo "Applying CRDs for LB Controller..."
+      #- kubectl apply -f LB-Controller/crds.yaml --kubeconfig /root/.kube/config
+      #- echo "Checking if ServiceAccount aws-load-balancer-controller exists..."
+      #- SA_NAME=$(kubectl get serviceaccount aws-load-balancer-controller -n kube-system -o jsonpath='{.metadata.name}' 2>/dev/null || echo "")
+      #- if [ -z "$SA_NAME" ]; then
+      #    echo "ServiceAccount not found, creating...";
+      #    kubectl create serviceaccount aws-load-balancer-controller -n kube-system;
+      #  else
+      #    echo "ServiceAccount already exists, skipping creation.";
+      #  fi
+      #- kubectl annotate serviceaccount aws-load-balancer-controller eks.amazonaws.com/role-arn=$EKS_LB_ROLE_ARN -n kube-system --overwrite
+      #- helm repo add eks https://aws.github.io/eks-charts
+      #- helm repo update
+      #- echo "Checking if Helm release aws-load-balancer-controller exists..."
+      #- helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller --namespace kube-system --set clusterName="$EKS_CLUSTER_NAME" --set serviceAccount.create=false --set serviceAccount.name=aws-load-balancer-controller --set region="$CLUSTER_REGION" --set vpcId="$VPC_ID";
+      #- echo "Waiting for aws-load-balancer-controller pod to be ready..."
+      #- kubectl wait --for=condition=Available deployment/aws-load-balancer-controller -n kube-system --timeout=300s
+      #- echo "aws-load-balancer-controller is now running. Applying nginx deployment..."
+      #- kubectl apply -f nginx/nginx.yaml
 
   post_build:
     commands:
-      - wget https://github.com/wso2/product-is/releases/download/v7.0.0/wso2is-7.0.0.zip
-      - sudo yum install unzip
-      - unzip wso2is-7.0.0
-      - cp wso2is-7.0.0/dbscripts .
+      #- wget https://github.com/wso2/product-is/releases/download/v7.0.0/wso2is-7.0.0.zip
+      #- sudo yum install unzip
+      #- unzip wso2is-7.0.0
+      - cp -r wso2is-7.0.0/dbscripts .
       - sh db-population/db.sh
       - echo "Verifying deployed resources..."
       - kubectl get pods -A --kubeconfig /root/.kube/config
