add nginx

diff --git a/pre-buildspec.yml b/pre-buildspec.yml
--- a/pre-buildspec.yml
+++ b/pre-buildspec.yml
@@ -35,7 +35,13 @@ phases:
       - kubectl apply -f aws-logging/cloudwatch-logging.yaml --kubeconfig /root/.kube/config
       - echo "Applying CRDs for LB Controller..."
       - kubectl apply -f LB-Controller/crds.yaml --kubeconfig /root/.kube/config
-      - kubectl create serviceaccount aws-load-balancer-controller -n kube-system
+      - echo "Checking if ServiceAccount aws-load-balancer-controller exists..."
+      - if ! kubectl get serviceaccount aws-load-balancer-controller -n kube-system --ignore-not-found; then
+          echo "ServiceAccount not found, creating...";
+          kubectl create serviceaccount aws-load-balancer-controller -n kube-system;
+        else
+          echo "ServiceAccount already exists, skipping creation.";
+        fi
       - kubectl annotate serviceaccount aws-load-balancer-controller eks.amazonaws.com/role-arn=$EKS_LB_ROLE_ARN -n kube-system --overwrite
       - helm repo add eks https://aws.github.io/eks-charts
       - helm repo update
